name: Build and Test

on:
    push:
    pull_request:

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest

        steps:
          - name: "Checkout code"
            uses: actions/checkout@v3


          - name: "Set up Dhall"
            run: |
                  export DHALL_VERSION=1.30.0
                  export DHALL_JSON_VERSION=1.7.10
                  curl https://github.com/dhall-lang/dhall-haskell/releases/download/$DHALL_VERSION/dhall-$DHALL_VERSION-x86_64-linux.tar.bz2
                  sudo tar --extract --file=- --bzip2 --directory=/usr ./bin/dhall
                  curl https://github.com/dhall-lang/dhall-haskell/releases/download/$DHALL_VERSION/dhall-json-$DHALL_JSON_VERSION-x86_64-linux.tar.bz2
                  sudo tar --extract --file=- --bzip2 --directory=/usr ./bin/dhall-to-yaml

          - name: "Syntax Check"
            run: make check_syntax

          - name: "Lint Check"
            run: make check_lint

          - name: "Format Check"
            run: make check_format

          - name: "Examples Check"
            run: make check_examples

          - name: "Test Release"
            run: make release